export const englishWordsArray: string[] = [
  'the',
  'be',
  'of',
  'and',
  'a',
  'to',
  'in',
  'he',
  'have',
  'it',
  'that',
  'for',
  'they',
  'i',
  'with',
  'as',
  'not',
  'on',
  'she',
  'at',
  'by',
  'this',
  'we',
  'you',
  'do',
  'but',
  'from',
  'or',
  'which',
  'one',
  'would',
  'all',
  'will',
  'there',
  'say',
  'who',
  'make',
  'when',
  'can',
  'more',
  'if',
  'no',
  'man',
  'out',
  'other',
  'so',
  'what',
  'time',
  'up',
  'go',
  'about',
  'than',
  'into',
  'could',
  'state',
  'only',
  'new',
  'year',
  'some',
  'take',
  'come',
  'these',
  'know',
  'see',
  'use',
  'get',
  'like',
  'then',
  'first',
  'any',
  'work',
  'now',
  'may',
  'such',
  'give',
  'over',
  'think',
  'most',
  'even',
  'find',
  'day',
  'also',
  'after',
  'way',
  'many',
  'must',
  'look',
  'before',
  'great',
  'back',
  'through',
  'long',
  'where',
  'much',
  'should',
  'well',
  'people',
  'down',
  'own',
  'just',
  'because',
  'good',
  'each',
  'those',
  'feel',
  'seem',
  'how',
  'high',
  'too',
  'place',
  'little',
  'world',
  'very',
  'still',
  'nation',
  'hand',
  'old',
  'life',
  'tell',
  'write',
  'become',
  'here',
  'show',
  'house',
  'both',
  'between',
  'need',
  'mean',
  'call',
  'develop',
  'under',
  'last',
  'right',
  'move',
  'thing',
  'general',
  'school',
  'never',
  'same',
  'another',
  'begin',
  'while',
  'number',
  'part',
  'turn',
  'real',
  'leave',
  'might',
  'want',
  'point',
  'form',
  'off',
  'child',
  'few',
  'small',
  'since',
  'against',
  'ask',
  'late',
  'home',
  'interest',
  'large',
  'person',
  'end',
  'open',
  'public',
  'follow',
  'during',
  'present',
  'without',
  'again',
  'hold',
  'govern',
  'around',
  'possible',
  'head',
  'consider',
  'word',
  'program',
  'problem',
  'however',
  'lead',
  'system',
  'set',
  'order',
  'eye',
  'plan',
  'run',
  'keep',
  'face',
  'fact',
  'group',
  'play',
  'stand',
  'increase',
  'early',
  'course',
  'change',
  'help',
  'line',
];

export const englishQuotesArray: string[] = [
  'The only way to do great work is to love what you do.',
  "Life is what happens when you're busy making other plans.",
  'Success is not final, failure is not fatal: It is the courage to continue that counts.',
  'Do not watch the clock; do what it does. Keep going.',
  'Dream big and dare to fail. Every setback is a setup for a greater comeback. The only way to grow is to step outside your comfort zone and take risks that challenge you.',
  'Believe you can and you’re halfway there. Your mind is the strongest tool you have—use it wisely. Confidence and determination will take you further than talent alone ever could.',
  'Difficulties in life are intended to make us better, not bitter. Grow through what you go through. Every challenge carries within it the seed of an opportunity to rise stronger.',
  'Opportunities don’t happen, you create them. Success comes to those who take action. If you wait for the perfect moment, you may wait forever—act now and shape your own path.',
  'Do what you can, with what you have, where you are. Small steps lead to big changes. The most successful people didn’t start with everything, they made the most of what they had.',
  'Act as if what you do makes a difference—because it does. Even the smallest effort can ripple outward. You never know whose life you are impacting with a kind word or action.',
  'Failure is simply the opportunity to begin again, this time more intelligently. Learn, adapt, improve. Each mistake brings a lesson, and each lesson brings you closer to success.',
  'Strength doesn’t come from what you can do, it comes from overcoming the things you once thought you couldn’t. True growth happens when you push beyond your limits and refuse to give up.',
  'A year from now, you may wish you had started today. Don’t wait—begin, even if it’s small. Progress is built one step at a time, and even the slowest climb is better than standing still.',
  'Be so good they can’t ignore you. Hard work, passion, and persistence will always be noticed. Talent is a gift, but perseverance and dedication are what truly set you apart from the rest.',
  'If you want to lift yourself up, lift up someone else.',
  'The best revenge is massive success.',
  'You must be the change you wish to see in the world.',
  "It always seems impossible until it's done.",
  'The only limit to our realization of tomorrow is our doubts of today.',
  'Happiness is not something ready-made. It comes from your own actions.',
  'The greatest glory in living lies not in never falling, but in rising every time we fall. That is the true test of character.',
  "In three words I can sum up everything I've learned about life: It goes on, no matter what struggles you face.",
  'Twenty years from now you will be more disappointed by the things you didn’t do than by the ones you did do.',
  'Our lives begin to end the day we become silent about things that matter. Speak up, even if your voice shakes.',
  'The future belongs to those who believe in the beauty of their dreams and have the courage to chase them relentlessly.',
  'Don’t judge each day by the harvest you reap but by the seeds that you plant for tomorrow’s growth.',
  'What lies behind us and what lies before us are tiny matters compared to what lies within us—our will, our spirit, our fight.',
  'If you look at what you have in life, you’ll always have more. If you look at what you don’t have, you’ll never have enough.',
  'I can’t change the direction of the wind, but I can adjust my sails to always reach my destination, no matter the storm.',
  'The man who moves a mountain begins by carrying away small stones—persistence beats talent when talent doesn’t work hard.',
  'Life is a series of natural and spontaneous changes. Don’t resist them; that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like, because the only constant in life is change, and fighting it will only make you tired and unhappy in the long run.',
  'Success is stumbling from failure to failure with no loss of enthusiasm. You have to keep trying, keep believing, and keep moving forward, because every wrong attempt discarded is another step forward toward something greater—something you might not even see coming until it suddenly makes sense.',
  'The biggest risk is not taking any risk. In a world that’s changing quickly, the only strategy that is guaranteed to fail is not taking chances. You have to be willing to fail, to be wrong, to embarrass yourself, because if you’re not failing, you’re not pushing your limits hard enough.',
  'Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma—which is living with the results of other people’s thinking. Don’t let the noise of others’ opinions drown out your own inner voice. Have the courage to follow your heart and intuition.',
  'I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. Kindness echoes through time, and the smallest act of compassion can change someone’s entire day—or even their life—without you ever realizing it.',
];

export const russianWordsArray: string[] = [
  'и',
  'в',
  'не',
  'он',
  'на',
  'я',
  'что',
  'тот',
  'быть',
  'с',
  'а',
  'весь',
  'это',
  'как',
  'она',
  'по',
  'но',
  'они',
  'к',
  'у',
  'ты',
  'из',
  'мы',
  'за',
  'вы',
  'так',
  'же',
  'от',
  'сказать',
  'этот',
  'который',
  'мочь',
  'человек',
  'о',
  'один',
  'еще',
  'бы',
  'такой',
  'только',
  'себя',
  'свое',
  'какой',
  'когда',
  'уже',
  'для',
  'вот',
  'кто',
  'да',
  'говорить',
  'год',
  'знать',
  'мой',
  'до',
  'или',
  'если',
  'время',
  'рука',
  'нет',
  'ни',
  'стать',
  'даже',
  'другой',
  'наш',
  'свой',
  'ну',
  'под',
  'где',
  'дело',
  'есть',
  'сам',
  'раз',
  'чтобы',
  'два',
  'там',
  'чем',
  'глаз',
  'жизнь',
  'первый',
  'день',
  'тут',
  'во',
  'ничто',
  'потом',
  'очень',
  'со',
  'хотеть',
  'ли',
  'при',
  'голова',
  'надо',
  'без',
  'видеть',
  'идти',
  'теперь',
  'тоже',
  'стоять',
  'друг',
  'дом',
  'можно',
  'после',
  'слово',
  'здесь',
  'думать',
  'место',
  'спросить',
  'через',
  'лицо',
  'тогда',
  'ведь',
  'хороший',
  'каждый',
  'новый',
  'жить',
  'должный',
  'смотреть',
  'почему',
  'потому',
  'сторона',
  'просто',
  'нога',
  'сидеть',
  'понять',
  'иметь',
  'конечный',
  'делать',
  'вдруг',
  'над',
  'взять',
  'никто',
  'сделать',
  'дверь',
  'перед',
  'понимать',
  'казаться',
  'работа',
  'ваш',
  'уж',
  'земля',
  'конец',
  'час',
  'город',
  'последний',
  'пока',
  'давать',
  'вода',
  'более',
  'хотя',
  'всегда',
  'куда',
  'пойти',
  'стол',
  'ребенок',
  'увидеть',
  'сила',
  'отец',
  'женщина',
  'машина',
  'ночь',
  'сразу',
  'мир',
  'совсем',
  'об',
  'вид',
  'выйти',
  'дать',
  'работать',
  'любить',
  'старый',
  'почти',
  'ряд',
  'оказаться',
  'начало',
  'твой',
  'вопрос',
  'много',
  'снова',
  'ответить',
  'между',
  'подумать',
  'опять',
  'белый',
  'деньги',
  'значить',
  'про',
  'лишь',
  'минута',
  'жена',
  'посмотреть',
  'правда',
  'главный',
  'страна',
  'свет',
  'ждать',
  'мать',
  'бывать',
  'кровать',
  'молчать',
  'показаться',
  'радоваться',
  'отказываться',
];

export const russianQuotesArray: string[] = [
  'Всё, что ты можешь себе представить, реально.',
  'Трудности — это то, что превращает обычные люди в необычных.',
  'Не бойтесь делать ошибки. Ошибки — это доказательство того, что вы пытаетесь.',
  'Успех — это не конечная точка, а путь к ней.',
  'Каждый день — это новая возможность изменить свою жизнь к лучшему.',
  'Не позволяйте страху перед неудачами остановить вас от достижения ваших целей.',
  'Секрет успеха заключается в том, чтобы начать действовать.',
  'Вы можете изменить свою жизнь, если измените свои мысли.',
  'Не ждите идеального момента. Берите момент и делайте его идеальным.',
  'Ваша жизнь — это результат ваших решений, а не обстоятельств.',
];
